# Generated by Django 5.0.10 on 2025-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igusers", "0002_post_likes_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="likes",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
