# Generated by Django 5.0.10 on 2025-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igusers", "0004_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="add_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
